default: &default
  adapter: postgresql
  encoding: unicode
  database: ca_development
  host: localhost
  pool: 5
  username: creative_assets
  password:
  host: localhost

development:
  <<: *default
  database: ca_development

test:
  <<: *default
  database: ca_test

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || 20 %>
